dist: trusty
language: python

python:
    - 3.5
    - 3.6
    - nightly

install:
    - pip install pipenv
    - pipenv install
    - pipenv shell
    - pipenv install coveralls pytest==3.6 pytest-cov pycodestyle pyspark

script:
    - export PYTHONPATH=${PYTHONPATH}:${PWD}
    - pycodestyle *.py tests/*.py
    - pytest

after_success:
- coveralls
